/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WorkLogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  logDirectory: "\u5DE5\u4F5C\u65E5\u5FD7",
  fileNameFormat: "{{year}}-\u5DE5\u4F5C\u65E5\u5FD7",
  dateFormat: "YYYY-MM-DD",
  weekStart: "monday",
  weekdayLanguage: "zh",
  autoGenerateYearStructure: true,
  timestampFormat: "HH:mm",
  showContentDots: true,
  calendarPosition: "right",
  fileHeaderTemplate: "# {{year}}\u5E74\u5DE5\u4F5C\u65E5\u5FD7"
};
var WorkLogSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5DE5\u4F5C\u65E5\u5FD7\u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u6587\u4EF6\u5B58\u50A8" });
    new import_obsidian.Setting(containerEl).setName("\u5B58\u50A8\u76EE\u5F55").setDesc("\u6240\u6709\u5E74\u5EA6\u6587\u4EF6\u5B58\u653E\u7684\u6587\u4EF6\u5939\uFF08\u76F8\u5BF9\u4ED3\u5E93\u6839\u76EE\u5F55\uFF09").addText(
      (text) => text.setPlaceholder("\u5DE5\u4F5C\u65E5\u5FD7").setValue(this.plugin.settings.logDirectory).onChange(async (value) => {
        this.plugin.settings.logDirectory = value.trim() || "\u5DE5\u4F5C\u65E5\u5FD7";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u4EF6\u540D\u683C\u5F0F").setDesc("\u652F\u6301 {{year}} \u53D8\u91CF\uFF0C\u4F8B\u5982\uFF1A{{year}}-\u5DE5\u4F5C\u65E5\u5FD7").addText(
      (text) => text.setPlaceholder("{{year}}-\u5DE5\u4F5C\u65E5\u5FD7").setValue(this.plugin.settings.fileNameFormat).onChange(async (value) => {
        this.plugin.settings.fileNameFormat = value.trim() || "{{year}}-\u5DE5\u4F5C\u65E5\u5FD7";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6587\u4EF6\u5934\u90E8\u6A21\u677F").setDesc("\u5E74\u5EA6\u6587\u4EF6\u7684\u7B2C\u4E00\u884C\u6807\u9898\uFF0C\u652F\u6301 {{year}} \u53D8\u91CF").addText(
      (text) => text.setPlaceholder("# {{year}}\u5E74\u5DE5\u4F5C\u65E5\u5FD7").setValue(this.plugin.settings.fileHeaderTemplate).onChange(async (value) => {
        this.plugin.settings.fileHeaderTemplate = value.trim() || "# {{year}}\u5E74\u5DE5\u4F5C\u65E5\u5FD7";
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u65E5\u671F\u4E0E\u65F6\u95F4" });
    new import_obsidian.Setting(containerEl).setName("\u65E5\u671F\u683C\u5F0F").setDesc("\u56DB\u7EA7\u6807\u9898\u4E2D\u65E5\u671F\u7684\u663E\u793A\u683C\u5F0F\uFF08Moment.js \u683C\u5F0F\uFF09\uFF0C\u9ED8\u8BA4 YYYY-MM-DD").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dateFormat).onChange(async (value) => {
        this.plugin.settings.dateFormat = value.trim() || "YYYY-MM-DD";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5468\u8D77\u59CB\u65E5").setDesc("\u6BCF\u5468\u4ECE\u54EA\u4E00\u5929\u5F00\u59CB").addDropdown(
      (dd) => dd.addOption("monday", "\u5468\u4E00").addOption("sunday", "\u5468\u65E5").setValue(this.plugin.settings.weekStart).onChange(async (value) => {
        this.plugin.settings.weekStart = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u661F\u671F\u51E0\u8BED\u8A00").setDesc("\u65E5\u671F\u6807\u9898\u4E2D\u661F\u671F\u51E0\u7684\u663E\u793A\u8BED\u8A00").addDropdown(
      (dd) => dd.addOption("zh", "\u4E2D\u6587\uFF08\u661F\u671F\u4E00\u2026\u661F\u671F\u65E5\uFF09").addOption("en", "\u82F1\u6587\uFF08Monday\u2026Sunday\uFF09").setValue(this.plugin.settings.weekdayLanguage).onChange(async (value) => {
        this.plugin.settings.weekdayLanguage = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u63D2\u5165\u65F6\u95F4\u6233\u683C\u5F0F").setDesc("\u5FEB\u901F\u63D2\u5165\u5DE5\u4F5C\u8BB0\u5F55\u65F6\u7684\u65F6\u95F4\u524D\u7F00\uFF08Moment.js \u683C\u5F0F\uFF09\uFF0C\u9ED8\u8BA4 HH:mm").addText(
      (text) => text.setPlaceholder("HH:mm").setValue(this.plugin.settings.timestampFormat).onChange(async (value) => {
        this.plugin.settings.timestampFormat = value.trim() || "HH:mm";
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u81EA\u52A8\u5316" });
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u751F\u6210\u5168\u5E74\u6846\u67B6").setDesc("\u6BCF\u5E74\u9996\u6B21\u6253\u5F00\u65F6\u81EA\u52A8\u751F\u6210\u5168\u5E74\u6240\u6709\u65E5\u671F\u7ED3\u6784").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoGenerateYearStructure).onChange(async (value) => {
        this.plugin.settings.autoGenerateYearStructure = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u65E5\u5386\u89C6\u56FE" });
    new import_obsidian.Setting(containerEl).setName("\u6807\u8BB0\u6709\u5185\u5BB9\u7684\u65E5\u671F").setDesc("\u5728\u65E5\u5386\u4E0A\u7528\u5706\u70B9\u6807\u8BB0\u6709\u5DE5\u4F5C\u5185\u5BB9\u7684\u65E5\u671F").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showContentDots).onChange(async (value) => {
        this.plugin.settings.showContentDots = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u65E5\u5386\u89C6\u56FE\u9ED8\u8BA4\u4F4D\u7F6E").addDropdown(
      (dd) => dd.addOption("right", "\u53F3\u4FA7\u8FB9\u680F").addOption("left", "\u5DE6\u4FA7\u8FB9\u680F").addOption("tab", "\u4E3B\u533A\u57DF\u6807\u7B7E\u9875").setValue(this.plugin.settings.calendarPosition).onChange(async (value) => {
        this.plugin.settings.calendarPosition = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/fileManager.ts
var import_obsidian3 = require("obsidian");

// src/dateUtils.ts
var import_obsidian2 = require("obsidian");
var ZH_MONTH_NAMES = [
  "",
  "\u4E00\u6708",
  "\u4E8C\u6708",
  "\u4E09\u6708",
  "\u56DB\u6708",
  "\u4E94\u6708",
  "\u516D\u6708",
  "\u4E03\u6708",
  "\u516B\u6708",
  "\u4E5D\u6708",
  "\u5341\u6708",
  "\u5341\u4E00\u6708",
  "\u5341\u4E8C\u6708"
];
var ZH_WEEKDAYS = ["\u661F\u671F\u65E5", "\u661F\u671F\u4E00", "\u661F\u671F\u4E8C", "\u661F\u671F\u4E09", "\u661F\u671F\u56DB", "\u661F\u671F\u4E94", "\u661F\u671F\u516D"];
var EN_WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
function formatWeekday(date, lang) {
  const dow = date.day();
  return lang === "zh" ? ZH_WEEKDAYS[dow] : EN_WEEKDAYS[dow];
}
function getMonthName(month) {
  return ZH_MONTH_NAMES[month] || `${month}\u6708`;
}
function buildYearStructure(year, settings) {
  const weekStartDay = settings.weekStart === "monday" ? 1 : 0;
  const start = (0, import_obsidian2.moment)({ year, month: 0, date: 1 });
  const end = (0, import_obsidian2.moment)({ year, month: 11, date: 31 });
  const weekMap = /* @__PURE__ */ new Map();
  const monthWeekKeys = /* @__PURE__ */ new Map();
  let cur = start.clone();
  while (cur.isSameOrBefore(end, "day")) {
    const month = cur.month() + 1;
    const wStart = getWeekStart(cur, weekStartDay);
    const wEnd = wStart.clone().add(6, "days");
    const weekKey = wStart.format("YYYY-MM-DD");
    if (!weekMap.has(weekKey)) {
      weekMap.set(weekKey, {
        weekIndex: 0,
        // 后面重新计算
        weekStart: wStart.clone(),
        weekEnd: wEnd.clone(),
        days: []
      });
    }
    const week = weekMap.get(weekKey);
    if (cur.year() === year) {
      week.days.push(cur.clone());
    }
    if (!monthWeekKeys.has(month)) {
      monthWeekKeys.set(month, /* @__PURE__ */ new Set());
    }
    monthWeekKeys.get(month).add(weekKey);
    cur.add(1, "day");
  }
  const allWeekKeys = Array.from(weekMap.keys()).sort();
  allWeekKeys.forEach((key, idx) => {
    weekMap.get(key).weekIndex = idx + 1;
  });
  const monthGroups = [];
  for (let month = 1; month <= 12; month++) {
    const keys = monthWeekKeys.get(month);
    if (!keys)
      continue;
    const sortedKeys = Array.from(keys).sort();
    const weeks = sortedKeys.map((k) => weekMap.get(k)).filter(Boolean);
    monthGroups.push({
      month,
      monthName: getMonthName(month),
      weeks
    });
  }
  return monthGroups;
}
function getWeekStart(date, weekStartDay) {
  const dow = date.day();
  let diff = dow - weekStartDay;
  if (diff < 0)
    diff += 7;
  return date.clone().subtract(diff, "days");
}
function formatWeekTitle(wg, year) {
  const s = wg.weekStart;
  const e = wg.weekEnd;
  const fmtDate = (d) => {
    return `${d.month() + 1}\u6708${d.date()}\u65E5`;
  };
  return `\u7B2C${wg.weekIndex}\u5468\uFF08${fmtDate(s)} - ${fmtDate(e)}\uFF09`;
}
function formatDayTitle(date, settings) {
  const dateStr = date.format(settings.dateFormat);
  const weekday = formatWeekday(date, settings.weekdayLanguage);
  return `${dateStr} ${weekday}`;
}
function parseDayTitle(heading, dateFormat) {
  const stripped = heading.replace(/^####\s+/, "").trim();
  const datePart = stripped.split(/\s+/)[0];
  const m = (0, import_obsidian2.moment)(datePart, dateFormat, true);
  return m.isValid() ? m : null;
}
function isSameDay(a, b) {
  return a.isSame(b, "day");
}
function formatMonthHeading(month) {
  return getMonthName(month);
}

// src/fileManager.ts
var FileManager = class {
  constructor(app, settings) {
    /** 内存缓存 */
    this.cache = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  // ─────────────────────────────────────────────────────
  // 文件路径
  // ─────────────────────────────────────────────────────
  getFileName(year) {
    return this.settings.fileNameFormat.replace("{{year}}", String(year));
  }
  getFilePath(year) {
    const dir = this.settings.logDirectory;
    const name = this.getFileName(year);
    return (0, import_obsidian3.normalizePath)(`${dir}/${name}.md`);
  }
  async getOrCreateFile(year) {
    const filePath = this.getFilePath(year);
    let file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file) {
      await this.ensureDirectory(this.settings.logDirectory);
      const content = this.settings.autoGenerateYearStructure ? await this.generateFullYearContent(year) : this.generateFileHeader(year);
      file = await this.app.vault.create(filePath, content);
      new import_obsidian3.Notice(`\u5DF2\u521B\u5EFA ${year} \u5E74\u5DE5\u4F5C\u65E5\u5FD7\u6587\u4EF6`);
    }
    return file;
  }
  async ensureDirectory(dir) {
    const normalized = (0, import_obsidian3.normalizePath)(dir);
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (!existing) {
      await this.app.vault.createFolder(normalized);
    }
  }
  // ─────────────────────────────────────────────────────
  // 内容生成
  // ─────────────────────────────────────────────────────
  generateFileHeader(year) {
    return this.settings.fileHeaderTemplate.replace("{{year}}", String(year)) + "\n";
  }
  async generateFullYearContent(year) {
    const groups = buildYearStructure(year, this.settings);
    const lines = [];
    lines.push(this.generateFileHeader(year).trimEnd());
    lines.push("");
    for (const mg of groups) {
      lines.push(`## ${formatMonthHeading(mg.month)}`);
      lines.push("");
      for (const wg of mg.weeks) {
        lines.push(`### ${formatWeekTitle(wg, year)}`);
        lines.push("");
        for (const day of wg.days) {
          lines.push(`#### ${formatDayTitle(day, this.settings)}`);
          lines.push("");
        }
      }
    }
    return lines.join("\n");
  }
  // ─────────────────────────────────────────────────────
  // 缓存管理
  // ─────────────────────────────────────────────────────
  /** 解析文件，建立 日期字符串→行号 的缓存 */
  async buildCache(file) {
    const year = this.extractYearFromFile(file);
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const dateMap = /* @__PURE__ */ new Map();
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith("#### ")) {
        const m = parseDayTitle(line, this.settings.dateFormat);
        if (m && m.isValid()) {
          dateMap.set(m.format("YYYY-MM-DD"), i);
        }
      }
    }
    if (year) {
      this.cache.set(year, dateMap);
    }
    return dateMap;
  }
  invalidateCache(year) {
    this.cache.delete(String(year));
  }
  extractYearFromFile(file) {
    const m = file.basename.match(/(\d{4})/);
    return m ? m[1] : null;
  }
  async getDateLineMap(file) {
    const year = this.extractYearFromFile(file);
    if (year && this.cache.has(year)) {
      return this.cache.get(year);
    }
    return this.buildCache(file);
  }
  // ─────────────────────────────────────────────────────
  // 日期定位与创建
  // ─────────────────────────────────────────────────────
  /**
   * 打开文件并跳转到指定日期标题
   * 若不存在则先创建缺失的日期结构
   */
  async openAndNavigateToDate(date) {
    const year = date.year();
    const file = await this.getOrCreateFile(year);
    let lineMap = await this.getDateLineMap(file);
    const dateKey = date.format("YYYY-MM-DD");
    if (!lineMap.has(dateKey)) {
      await this.insertMissingDateBlock(file, date);
      lineMap = await this.buildCache(file);
    }
    const lineNo = lineMap.get(dateKey);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    if (lineNo !== void 0) {
      this.scrollToLineWithRetry(leaf, lineNo, 0);
    }
  }
  /**
   * 在文件中插入缺失的日期区块，保持月/周/日结构完整
   */
  async insertMissingDateBlock(file, date) {
    const year = date.year();
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const groups = buildYearStructure(year, this.settings);
    const month = date.month() + 1;
    const targetMg = groups.find((mg) => mg.month === month);
    if (!targetMg)
      return;
    const dateKey = date.format("YYYY-MM-DD");
    const targetWg = targetMg.weeks.find(
      (wg) => wg.days.some((d) => d.format("YYYY-MM-DD") === dateKey)
    );
    if (!targetWg)
      return;
    const monthHeading = `## ${formatMonthHeading(month)}`;
    const monthLineIdx = lines.findIndex((l) => l.trim() === monthHeading);
    if (monthLineIdx === -1) {
      await this.insertMonthBlock(file, targetMg, groups, year);
    } else {
      const weekTitle = `### ${formatWeekTitle(targetWg, year)}`;
      const weekLineIdx = lines.findIndex((l) => l.trim() === weekTitle);
      if (weekLineIdx === -1) {
        await this.insertWeekBlock(file, targetMg, targetWg, month, year);
      } else {
        await this.insertDayHeading(file, date, targetWg, year);
      }
    }
    this.invalidateCache(year);
  }
  async insertDayHeading(file, date, wg, year) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const dateKey = date.format("YYYY-MM-DD");
    const weekTitle = `### ${formatWeekTitle(wg, year)}`;
    const weekLineIdx = lines.findIndex((l) => l.trim() === weekTitle);
    if (weekLineIdx === -1)
      return;
    let insertIdx = weekLineIdx + 1;
    while (insertIdx < lines.length && lines[insertIdx].trim() === "") {
      insertIdx++;
    }
    for (let i = insertIdx; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith("## ") || line.startsWith("### "))
        break;
      if (line.startsWith("#### ")) {
        const m = parseDayTitle(line, this.settings.dateFormat);
        if (m && m.isValid() && m.format("YYYY-MM-DD") > dateKey) {
          insertIdx = i;
          break;
        }
        insertIdx = i + 1;
      }
    }
    const dayHeading = `#### ${formatDayTitle(date, this.settings)}`;
    lines.splice(insertIdx, 0, dayHeading, "");
    await this.app.vault.modify(file, lines.join("\n"));
  }
  async insertWeekBlock(file, mg, wg, month, year) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const monthHeading = `## ${formatMonthHeading(month)}`;
    const monthLineIdx = lines.findIndex((l) => l.trim() === monthHeading);
    if (monthLineIdx === -1)
      return;
    let insertIdx = monthLineIdx + 1;
    const weekTitle = `### ${formatWeekTitle(wg, year)}`;
    for (let i = monthLineIdx + 1; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith("## ")) {
        insertIdx = i;
        break;
      }
      if (line.startsWith("### ")) {
        const wMatch = line.match(/第(\d+)周/);
        if (wMatch && parseInt(wMatch[1]) > wg.weekIndex) {
          insertIdx = i;
          break;
        }
        insertIdx = i + 1;
      }
    }
    const weekLines = ["", `### ${formatWeekTitle(wg, year)}`, ""];
    for (const day of wg.days) {
      weekLines.push(`#### ${formatDayTitle(day, this.settings)}`);
      weekLines.push("");
    }
    lines.splice(insertIdx, 0, ...weekLines);
    await this.app.vault.modify(file, lines.join("\n"));
  }
  async insertMonthBlock(file, mg, allGroups, year) {
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    let insertIdx = lines.length;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (line.startsWith("## ")) {
        const existingMonth = allGroups.findIndex(
          (g) => `## ${formatMonthHeading(g.month)}` === line.trim()
        );
        if (existingMonth !== -1 && allGroups[existingMonth].month > mg.month) {
          insertIdx = i;
          break;
        }
      }
    }
    const monthLines = ["", `## ${formatMonthHeading(mg.month)}`, ""];
    for (const wg of mg.weeks) {
      monthLines.push(`### ${formatWeekTitle(wg, year)}`);
      monthLines.push("");
      for (const day of wg.days) {
        monthLines.push(`#### ${formatDayTitle(day, this.settings)}`);
        monthLines.push("");
      }
    }
    lines.splice(insertIdx, 0, ...monthLines);
    await this.app.vault.modify(file, lines.join("\n"));
  }
  // ─────────────────────────────────────────────────────
  // 滚动定位工具（多次重试，确保大文件编辑器就绪）
  // ─────────────────────────────────────────────────────
  scrollToLineWithRetry(leaf, lineNo, attempt) {
    const view = leaf.view;
    const editor = view == null ? void 0 : view.editor;
    if (editor && editor.lineCount() > lineNo) {
      editor.setCursor({ line: lineNo, ch: 0 });
      editor.scrollIntoView(
        { from: { line: lineNo, ch: 0 }, to: { line: lineNo, ch: 0 } },
        true
      );
      return;
    }
    if (attempt < 10) {
      setTimeout(() => this.scrollToLineWithRetry(leaf, lineNo, attempt + 1), 150);
    }
  }
  // ─────────────────────────────────────────────────────
  // 结构修复
  // ─────────────────────────────────────────────────────
  /**
   * 修复当前年度文件结构：补全缺失的月份/周/日期标题，不覆盖已有内容
   */
  async repairYearStructure(year) {
    const file = await this.getOrCreateFile(year);
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const groups = buildYearStructure(year, this.settings);
    const existingMonths = /* @__PURE__ */ new Set();
    const existingWeeks = /* @__PURE__ */ new Set();
    const existingDays = /* @__PURE__ */ new Set();
    for (const line of lines) {
      if (line.startsWith("## "))
        existingMonths.add(line.trim());
      if (line.startsWith("### "))
        existingWeeks.add(line.trim());
      if (line.startsWith("#### ")) {
        const m = parseDayTitle(line, this.settings.dateFormat);
        if (m)
          existingDays.add(m.format("YYYY-MM-DD"));
      }
    }
    let repaired = 0;
    for (const mg of groups) {
      const monthHeading = `## ${formatMonthHeading(mg.month)}`;
      if (!existingMonths.has(monthHeading)) {
        await this.insertMonthBlock(file, mg, groups, year);
        repaired++;
        continue;
      }
      for (const wg of mg.weeks) {
        const weekHeading = `### ${formatWeekTitle(wg, year)}`;
        if (!existingWeeks.has(weekHeading)) {
          await this.insertWeekBlock(file, mg, wg, mg.month, year);
          repaired++;
          continue;
        }
        for (const day of wg.days) {
          const dateKey = day.format("YYYY-MM-DD");
          if (!existingDays.has(dateKey)) {
            await this.insertDayHeading(file, day, wg, year);
            repaired++;
          }
        }
      }
    }
    this.invalidateCache(year);
    new import_obsidian3.Notice(`\u7ED3\u6784\u4FEE\u590D\u5B8C\u6210\uFF0C\u8865\u5168\u4E86 ${repaired} \u5904\u7F3A\u5931\u6807\u9898`);
  }
  // ─────────────────────────────────────────────────────
  // 快速插入条目
  // ─────────────────────────────────────────────────────
  /**
   * 在指定日期区块下追加工作记录标签（上午/下午）
   */
  async insertSessionLabel(date, label) {
    const file = await this.getOrCreateFile(date.year());
    let lineMap = await this.getDateLineMap(file);
    const dateKey = date.format("YYYY-MM-DD");
    if (!lineMap.has(dateKey)) {
      await this.insertMissingDateBlock(file, date);
      lineMap = await this.buildCache(file);
    }
    const headingLine = lineMap.get(dateKey);
    if (headingLine === void 0) {
      new import_obsidian3.Notice("\u65E0\u6CD5\u5B9A\u4F4D\u65E5\u671F\u6807\u9898");
      return;
    }
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const entry = `- ${label}`;
    let insertIdx = headingLine + 1;
    for (let i = headingLine + 1; i < lines.length; i++) {
      if (lines[i].startsWith("## ") || lines[i].startsWith("### ") || lines[i].startsWith("#### ")) {
        break;
      }
      if (lines[i].trim() !== "") {
        insertIdx = i + 1;
      } else {
        insertIdx = i;
      }
    }
    lines.splice(insertIdx, 0, entry);
    await this.app.vault.modify(file, lines.join("\n"));
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    this.scrollToLineWithRetry(leaf, insertIdx, 0);
    setTimeout(() => {
      const view = leaf.view;
      if (view == null ? void 0 : view.editor) {
        view.editor.setCursor({ line: insertIdx, ch: entry.length });
        view.editor.focus();
      }
    }, 300);
    this.invalidateCache(date.year());
  }
  /**
   * 在指定日期区块下追加带时间戳的工作条目
   */
  async insertTimestampEntry(customDate) {
    const today = customDate || (0, import_obsidian3.moment)();
    const file = await this.getOrCreateFile(today.year());
    let lineMap = await this.getDateLineMap(file);
    const dateKey = today.format("YYYY-MM-DD");
    if (!lineMap.has(dateKey)) {
      await this.insertMissingDateBlock(file, today);
      lineMap = await this.buildCache(file);
    }
    const headingLine = lineMap.get(dateKey);
    if (headingLine === void 0) {
      new import_obsidian3.Notice("\u65E0\u6CD5\u5B9A\u4F4D\u65E5\u671F\u6807\u9898");
      return;
    }
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const timestamp = (0, import_obsidian3.moment)().format(this.settings.timestampFormat);
    const entry = `- ${timestamp} `;
    let insertIdx = headingLine + 1;
    for (let i = headingLine + 1; i < lines.length; i++) {
      if (lines[i].startsWith("## ") || lines[i].startsWith("### ") || lines[i].startsWith("#### ")) {
        break;
      }
      if (lines[i].trim() !== "") {
        insertIdx = i + 1;
      } else {
        insertIdx = i;
      }
    }
    lines.splice(insertIdx, 0, entry);
    await this.app.vault.modify(file, lines.join("\n"));
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    this.scrollToLineWithRetry(leaf, insertIdx, 0);
    setTimeout(() => {
      const view = leaf.view;
      if (view == null ? void 0 : view.editor) {
        view.editor.setCursor({ line: insertIdx, ch: entry.length });
        view.editor.focus();
      }
    }, 300);
    this.invalidateCache(today.year());
  }
  // ─────────────────────────────────────────────────────
  // 内容统计（供日历视图和统计面板使用）
  // ─────────────────────────────────────────────────────
  /**
   * 获取某年某月有内容的日期集合
   */
  async getDatesWithContent(year, month) {
    const filePath = this.getFilePath(year);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file)
      return /* @__PURE__ */ new Set();
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const result = /* @__PURE__ */ new Set();
    let currentDate = null;
    let hasContent = false;
    for (const line of lines) {
      if (line.startsWith("#### ")) {
        if (currentDate && hasContent) {
          result.add(currentDate);
        }
        const m = parseDayTitle(line, this.settings.dateFormat);
        if (m && m.isValid() && m.year() === year && m.month() + 1 === month) {
          currentDate = m.format("YYYY-MM-DD");
          hasContent = false;
        } else {
          currentDate = null;
        }
      } else if (currentDate && !line.startsWith("## ") && !line.startsWith("### ") && line.trim() !== "") {
        hasContent = true;
      }
    }
    if (currentDate && hasContent) {
      result.add(currentDate);
    }
    return result;
  }
  /**
   * 获取某日期的前几行工作内容（用于 hover 预览）
   */
  async getDayPreview(date, maxLines = 4) {
    const year = date.year();
    const filePath = this.getFilePath(year);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file)
      return "";
    const lineMap = await this.getDateLineMap(file);
    const dateKey = date.format("YYYY-MM-DD");
    const headingLine = lineMap.get(dateKey);
    if (headingLine === void 0)
      return "";
    const content = await this.app.vault.read(file);
    const lines = content.split("\n");
    const previewLines = [];
    for (let i = headingLine + 1; i < lines.length && previewLines.length < maxLines; i++) {
      const line = lines[i];
      if (line.startsWith("## ") || line.startsWith("### ") || line.startsWith("#### "))
        break;
      if (line.trim() !== "") {
        previewLines.push(line.trim());
      }
    }
    return previewLines.join("\n");
  }
  // ─────────────────────────────────────────────────────
  // 导出
  // ─────────────────────────────────────────────────────
  async exportRange(year, format, month) {
    const filePath = this.getFilePath(year);
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file)
      return "";
    const content = await this.app.vault.read(file);
    if (format === "markdown") {
      if (month === void 0)
        return content;
      return this.extractMonthContent(content, month);
    }
    if (format === "html") {
      const md = month !== void 0 ? this.extractMonthContent(content, month) : content;
      return this.markdownToSimpleHtml(md, year, month);
    }
    if (format === "json") {
      return this.contentToJson(content, year, month);
    }
    return content;
  }
  extractMonthContent(content, month) {
    const monthHeading = `## ${this.getMonthName(month)}`;
    const lines = content.split("\n");
    let inMonth = false;
    const result = [];
    for (const line of lines) {
      if (line.trim() === monthHeading) {
        inMonth = true;
        result.push(line);
        continue;
      }
      if (inMonth) {
        if (line.startsWith("## ") && line.trim() !== monthHeading) {
          break;
        }
        result.push(line);
      }
    }
    return result.join("\n");
  }
  getMonthName(month) {
    const names = [
      "",
      "\u4E00\u6708",
      "\u4E8C\u6708",
      "\u4E09\u6708",
      "\u56DB\u6708",
      "\u4E94\u6708",
      "\u516D\u6708",
      "\u4E03\u6708",
      "\u516B\u6708",
      "\u4E5D\u6708",
      "\u5341\u6708",
      "\u5341\u4E00\u6708",
      "\u5341\u4E8C\u6708"
    ];
    return names[month] || `${month}\u6708`;
  }
  markdownToSimpleHtml(md, year, month) {
    const title = month ? `${year}\u5E74${this.getMonthName(month)}\u5DE5\u4F5C\u65E5\u5FD7` : `${year}\u5E74\u5DE5\u4F5C\u65E5\u5FD7`;
    let body = md.replace(/^#### (.+)$/gm, "<h4>$1</h4>").replace(/^### (.+)$/gm, "<h3>$1</h3>").replace(/^## (.+)$/gm, "<h2>$1</h2>").replace(/^# (.+)$/gm, "<h1>$1</h1>").replace(/^- \[x\] (.+)$/gm, '<li class="done">\u2705 $1</li>').replace(/^- \[ \] (.+)$/gm, '<li class="todo">\u2B1C $1</li>').replace(/^- (.+)$/gm, "<li>$1</li>").replace(/\n{2,}/g, "\n<br>\n");
    return `<!DOCTYPE html>
<html lang="zh">
<head><meta charset="UTF-8"><title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; }
  h1 { border-bottom: 2px solid #333; }
  h2 { color: #444; border-left: 4px solid #7c3aed; padding-left: 8px; }
  h3 { color: #666; }
  h4 { color: #888; }
  li { margin: 4px 0; }
  li.done { color: #22c55e; }
</style>
</head>
<body>${body}</body>
</html>`;
  }
  contentToJson(content, year, month) {
    const lines = content.split("\n");
    const result = {};
    let currentDate = null;
    for (const line of lines) {
      if (line.startsWith("#### ")) {
        const m = parseDayTitle(line, this.settings.dateFormat);
        if (m && m.isValid()) {
          if (month !== void 0 && m.month() + 1 !== month) {
            currentDate = null;
            continue;
          }
          currentDate = m.format("YYYY-MM-DD");
          result[currentDate] = [];
        }
      } else if (currentDate && !line.startsWith("## ") && !line.startsWith("### ") && line.trim() !== "") {
        result[currentDate].push(line.trim());
      }
    }
    return JSON.stringify({ year, month: month != null ? month : null, data: result }, null, 2);
  }
  // ─────────────────────────────────────────────────────
  // 搜索
  // ─────────────────────────────────────────────────────
  async searchAllLogs(keyword) {
    const dir = this.settings.logDirectory;
    const folder = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(dir));
    if (!(folder instanceof import_obsidian3.TFolder))
      return [];
    const results = [];
    for (const child of folder.children) {
      if (!(child instanceof import_obsidian3.TFile) || child.extension !== "md")
        continue;
      const content = await this.app.vault.read(child);
      const lines = content.split("\n");
      let currentDate = null;
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.startsWith("#### ")) {
          const m = parseDayTitle(line, this.settings.dateFormat);
          currentDate = m ? m.format("YYYY-MM-DD") : null;
        } else if (currentDate && line.toLowerCase().includes(keyword.toLowerCase())) {
          results.push({
            date: currentDate,
            content: line.trim(),
            filePath: child.path
          });
        }
      }
    }
    return results;
  }
};

// src/calendarView.ts
var import_obsidian4 = require("obsidian");
var CALENDAR_VIEW_TYPE = "work-log-calendar";
var CalendarView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    // 1-12
    this.selectedDate = null;
    this.tooltip = null;
    this.plugin = plugin;
    const now = (0, import_obsidian4.moment)();
    this.currentYear = now.year();
    this.currentMonth = now.month() + 1;
    this.selectedDate = now.clone();
  }
  getViewType() {
    return CALENDAR_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u5DE5\u4F5C\u65E5\u5FD7\u65E5\u5386";
  }
  getIcon() {
    return "calendar-days";
  }
  async onOpen() {
    await this.refresh();
  }
  async onClose() {
    this.removeTooltip();
  }
  async refresh() {
    try {
      await this.plugin.fileManager.getOrCreateFile(this.currentYear);
    } catch (e) {
    }
    await this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("work-log-calendar");
    const datesWithContent = await this.plugin.fileManager.getDatesWithContent(
      this.currentYear,
      this.currentMonth
    );
    this.renderHeader(container);
    this.renderCalendarGrid(container, datesWithContent);
    this.renderActionButton(container);
  }
  // ─────────────────────────────────────────────────────
  // Header
  // ─────────────────────────────────────────────────────
  renderHeader(container) {
    const header = container.createDiv("wl-cal-header");
    const prevBtn = header.createEl("button", { cls: "wl-nav-btn", text: "\u2039" });
    prevBtn.title = "\u4E0A\u4E00\u6708";
    prevBtn.addEventListener("click", () => this.navigateMonth(-1));
    const titleArea = header.createDiv("wl-cal-title");
    const now = (0, import_obsidian4.moment)();
    const yearSel = titleArea.createEl("select", { cls: "wl-year-select" });
    const startYear = now.year() - 5;
    const endYear = now.year() + 2;
    for (let y = startYear; y <= endYear; y++) {
      const opt = yearSel.createEl("option", { value: String(y), text: String(y) });
      if (y === this.currentYear)
        opt.selected = true;
    }
    yearSel.addEventListener("change", async (e) => {
      this.currentYear = parseInt(e.target.value);
      await this.refresh();
    });
    titleArea.createSpan({ text: "\u5E74", cls: "wl-title-sep" });
    const monthSel = titleArea.createEl("select", { cls: "wl-month-select" });
    const monthNames = [
      "\u4E00\u6708",
      "\u4E8C\u6708",
      "\u4E09\u6708",
      "\u56DB\u6708",
      "\u4E94\u6708",
      "\u516D\u6708",
      "\u4E03\u6708",
      "\u516B\u6708",
      "\u4E5D\u6708",
      "\u5341\u6708",
      "\u5341\u4E00\u6708",
      "\u5341\u4E8C\u6708"
    ];
    for (let m = 1; m <= 12; m++) {
      const opt = monthSel.createEl("option", { value: String(m), text: monthNames[m - 1] });
      if (m === this.currentMonth)
        opt.selected = true;
    }
    monthSel.addEventListener("change", async (e) => {
      this.currentMonth = parseInt(e.target.value);
      await this.refresh();
    });
    const nextBtn = header.createEl("button", { cls: "wl-nav-btn", text: "\u203A" });
    nextBtn.title = "\u4E0B\u4E00\u6708";
    nextBtn.addEventListener("click", () => this.navigateMonth(1));
    const todayBtn = header.createEl("button", { cls: "wl-today-btn", text: "\u4ECA\u65E5" });
    todayBtn.addEventListener("click", async () => {
      const n = (0, import_obsidian4.moment)();
      this.currentYear = n.year();
      this.currentMonth = n.month() + 1;
      this.selectedDate = n.clone();
      await this.refresh();
      await this.plugin.fileManager.openAndNavigateToDate(n);
    });
  }
  async navigateMonth(delta) {
    let m = this.currentMonth + delta;
    let y = this.currentYear;
    if (m < 1) {
      m = 12;
      y--;
    }
    if (m > 12) {
      m = 1;
      y++;
    }
    this.currentMonth = m;
    this.currentYear = y;
    await this.refresh();
  }
  // ─────────────────────────────────────────────────────
  // Calendar grid
  // ─────────────────────────────────────────────────────
  renderCalendarGrid(container, datesWithContent) {
    const grid = container.createDiv("wl-cal-grid");
    const weekStartDay = this.plugin.settings.weekStart;
    const headers = weekStartDay === "monday" ? ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u65E5"] : ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
    const headerRow = grid.createDiv("wl-cal-row wl-cal-weekdays");
    for (const h of headers) {
      headerRow.createDiv({ cls: "wl-cal-cell wl-weekday-header", text: h });
    }
    const firstDay = (0, import_obsidian4.moment)({ year: this.currentYear, month: this.currentMonth - 1, date: 1 });
    const lastDay = firstDay.clone().endOf("month");
    const today = (0, import_obsidian4.moment)();
    const dowFirst = firstDay.day();
    let startOffset;
    if (weekStartDay === "monday") {
      startOffset = (dowFirst + 6) % 7;
    } else {
      startOffset = dowFirst;
    }
    let dayRow = grid.createDiv("wl-cal-row");
    let cellCount = 0;
    for (let i = 0; i < startOffset; i++) {
      dayRow.createDiv("wl-cal-cell wl-cal-empty");
      cellCount++;
    }
    let cur = firstDay.clone();
    while (cur.isSameOrBefore(lastDay, "day")) {
      if (cellCount > 0 && cellCount % 7 === 0) {
        dayRow = grid.createDiv("wl-cal-row");
      }
      const isToday = isSameDay(cur, today);
      const isWeekend = cur.day() === 0 || cur.day() === 6;
      let selectedCls = "";
      if (this.selectedDate && isSameDay(cur, this.selectedDate)) {
        selectedCls = "wl-selected";
      }
      const cell = dayRow.createDiv({
        cls: [
          "wl-cal-cell",
          "wl-cal-day",
          isToday ? "wl-today" : "",
          isWeekend ? "wl-weekend" : "",
          selectedCls
        ].filter(Boolean).join(" ")
      });
      cell.createSpan({ cls: "wl-day-num", text: String(cur.date()) });
      if (datesWithContent.has(cur.format("YYYY-MM-DD"))) {
        cell.addClass("wl-has-content");
        cell.createDiv("wl-dot");
      }
      const dateCopy = cur.clone();
      cell.addEventListener("click", async () => {
        this.selectedDate = dateCopy.clone();
        await this.render();
        await this.plugin.fileManager.openAndNavigateToDate(dateCopy);
      });
      if (!this.app.isMobile) {
        cell.addEventListener("mouseenter", async (e) => {
          await this.showTooltip(e, dateCopy);
        });
        cell.addEventListener("mouseleave", () => {
          this.removeTooltip();
        });
      }
      cur.add(1, "day");
      cellCount++;
    }
    const remaining = cellCount % 7;
    if (remaining !== 0) {
      for (let i = remaining; i < 7; i++) {
        dayRow.createDiv("wl-cal-cell wl-cal-empty");
      }
    }
  }
  // ─────────────────────────────────────────────────────
  // Action button below calendar
  // ─────────────────────────────────────────────────────
  renderActionButton(container) {
    const actionBar = container.createDiv("wl-action-bar");
    const today = (0, import_obsidian4.moment)();
    let targetDate;
    let label;
    if (this.selectedDate && isSameDay(this.selectedDate, today)) {
      targetDate = today.clone();
      label = "\uFF0B \u6DFB\u52A0\u4ECA\u65E5\u5DE5\u4F5C\u8BB0\u5F55";
    } else if (this.selectedDate) {
      targetDate = this.selectedDate.clone();
      label = `\uFF0B \u6DFB\u52A0 ${targetDate.format("MM-DD")} \u5DE5\u4F5C\u8BB0\u5F55`;
    } else {
      targetDate = today.clone();
      label = "\uFF0B \u6DFB\u52A0\u4ECA\u65E5\u5DE5\u4F5C\u8BB0\u5F55";
    }
    const btn = actionBar.createEl("button", { cls: "wl-add-btn" });
    btn.textContent = label;
    const popup = actionBar.createDiv("wl-session-popup");
    popup.style.display = "none";
    const amBtn = popup.createEl("button", { cls: "wl-session-opt wl-session-am" });
    amBtn.textContent = "\u2600 \u4E0A\u5348";
    amBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.plugin.fileManager.insertSessionLabel(targetDate, "\u4E0A\u5348");
      await this.render();
    });
    const pmBtn = popup.createEl("button", { cls: "wl-session-opt wl-session-pm" });
    pmBtn.textContent = "\u{1F319} \u4E0B\u5348";
    pmBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.plugin.fileManager.insertSessionLabel(targetDate, "\u4E0B\u5348");
      await this.render();
    });
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      const isVisible = popup.style.display !== "none";
      popup.style.display = isVisible ? "none" : "flex";
    });
    document.addEventListener("click", (ev) => {
      if (!actionBar.contains(ev.target)) {
        popup.style.display = "none";
      }
    });
  }
  // ─────────────────────────────────────────────────────
  // Tooltip (desktop only)
  // ─────────────────────────────────────────────────────
  async showTooltip(e, date) {
    this.removeTooltip();
    const preview = await this.plugin.fileManager.getDayPreview(date, 5);
    if (!preview)
      return;
    const tt = document.createElement("div");
    tt.className = "wl-tooltip";
    tt.style.left = `${e.pageX + 12}px`;
    tt.style.top = `${e.pageY + 4}px`;
    tt.createDiv({ cls: "wl-tt-title", text: date.format("YYYY-MM-DD") });
    const body = tt.createDiv({ cls: "wl-tt-body" });
    preview.split("\n").forEach((line) => {
      body.createDiv({ cls: "wl-tt-line", text: line });
    });
    document.body.appendChild(tt);
    this.tooltip = tt;
  }
  removeTooltip() {
    if (this.tooltip && document.body.contains(this.tooltip)) {
      document.body.removeChild(this.tooltip);
    }
    this.tooltip = null;
  }
  // ─────────────────────────────────────────────────────
  // Public
  // ─────────────────────────────────────────────────────
  async navigateTo(year, month) {
    this.currentYear = year;
    this.currentMonth = month;
    await this.refresh();
  }
};

// src/statistics.ts
var import_obsidian5 = require("obsidian");
var SEARCH_VIEW_TYPE = "work-log-search";
async function getMonthStats(plugin, year, month) {
  const filePath = plugin.fileManager.getFilePath(year);
  const file = plugin.app.vault.getAbstractFileByPath(filePath);
  if (!file) {
    return { year, month, recordedDays: 0, totalEntries: 0, totalChars: 0, totalLines: 0 };
  }
  const content = await plugin.app.vault.read(file);
  const lines = content.split("\n");
  const datesWithContent = /* @__PURE__ */ new Set();
  let totalEntries = 0;
  let totalChars = 0;
  let totalLines = 0;
  let currentDateInMonth = false;
  for (const line of lines) {
    if (line.startsWith("#### ")) {
      const stripped = line.replace(/^####\s+/, "").trim();
      const datePart = stripped.split(/\s+/)[0];
      const m = (0, import_obsidian5.moment)(datePart, plugin.settings.dateFormat, true);
      if (m.isValid() && m.year() === year && m.month() + 1 === month) {
        currentDateInMonth = true;
        datesWithContent;
      } else {
        currentDateInMonth = false;
      }
    } else if (currentDateInMonth && !line.startsWith("## ") && !line.startsWith("### ") && line.trim() !== "") {
      const idx = lines.indexOf(line);
      for (let i = idx - 1; i >= 0; i--) {
        if (lines[i].startsWith("#### ")) {
          const stripped = lines[i].replace(/^####\s+/, "").trim();
          const datePart = stripped.split(/\s+/)[0];
          const m = (0, import_obsidian5.moment)(datePart, plugin.settings.dateFormat, true);
          if (m.isValid() && m.year() === year && m.month() + 1 === month) {
            datesWithContent.add(m.format("YYYY-MM-DD"));
          }
          break;
        }
      }
      totalEntries++;
      totalChars += line.length;
      totalLines++;
    }
  }
  return {
    year,
    month,
    recordedDays: datesWithContent.size,
    totalEntries,
    totalChars,
    totalLines
  };
}
var SearchView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.keyword = "";
    this.results = [];
    this.plugin = plugin;
  }
  getViewType() {
    return SEARCH_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u5DE5\u4F5C\u65E5\u5FD7\u641C\u7D22";
  }
  getIcon() {
    return "search";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("work-log-search");
    const searchHeader = container.createDiv("wl-search-header");
    searchHeader.createEl("h4", { text: "\u{1F50D} \u641C\u7D22\u5DE5\u4F5C\u65E5\u5FD7" });
    const inputRow = searchHeader.createDiv("wl-search-row");
    const input = inputRow.createEl("input", {
      type: "text",
      placeholder: "\u8F93\u5165\u5173\u952E\u8BCD\u2026",
      cls: "wl-search-input",
      value: this.keyword
    });
    const searchBtn = inputRow.createEl("button", { cls: "wl-search-btn", text: "\u641C\u7D22" });
    const doSearch = async () => {
      this.keyword = input.value.trim();
      if (!this.keyword)
        return;
      searchBtn.textContent = "\u641C\u7D22\u4E2D\u2026";
      searchBtn.disabled = true;
      this.results = await this.plugin.fileManager.searchAllLogs(this.keyword);
      this.renderResults(container);
      searchBtn.textContent = "\u641C\u7D22";
      searchBtn.disabled = false;
    };
    searchBtn.addEventListener("click", doSearch);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        doSearch();
    });
    this.renderResults(container);
  }
  renderResults(container) {
    const oldResults = container.querySelector(".wl-search-results");
    if (oldResults)
      container.removeChild(oldResults);
    const resultsEl = container.createDiv("wl-search-results");
    if (this.results.length === 0 && this.keyword) {
      resultsEl.createDiv({ cls: "wl-no-results", text: `\u672A\u627E\u5230\u5305\u542B"${this.keyword}"\u7684\u8BB0\u5F55` });
      return;
    }
    if (this.results.length === 0)
      return;
    resultsEl.createDiv({
      cls: "wl-result-count",
      text: `\u627E\u5230 ${this.results.length} \u6761\u7ED3\u679C`
    });
    const byDate = /* @__PURE__ */ new Map();
    for (const r of this.results) {
      if (!byDate.has(r.date))
        byDate.set(r.date, []);
      byDate.get(r.date).push(r);
    }
    const sortedDates = Array.from(byDate.keys()).sort().reverse();
    for (const date of sortedDates) {
      const group = resultsEl.createDiv("wl-result-group");
      const dateHeader = group.createDiv({ cls: "wl-result-date" });
      dateHeader.createSpan({ cls: "wl-result-date-icon", text: "\u{1F4C5}" });
      dateHeader.createSpan({ text: date });
      const items = byDate.get(date);
      for (const item of items) {
        const row = group.createDiv({ cls: "wl-result-item" });
        const highlighted = this.highlightKeyword(item.content, this.keyword);
        row.innerHTML = highlighted;
        row.addEventListener("click", async () => {
          const m = (0, import_obsidian5.moment)(date, "YYYY-MM-DD", true);
          if (m.isValid()) {
            await this.plugin.fileManager.openAndNavigateToDate(m);
          }
        });
      }
    }
  }
  highlightKeyword(text, keyword) {
    if (!keyword)
      return this.escapeHtml(text);
    const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`(${escaped})`, "gi");
    return this.escapeHtml(text).replace(re, '<mark class="wl-highlight">$1</mark>');
  }
  escapeHtml(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
};

// src/main.ts
var WorkLogPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.fileManager = new FileManager(this.app, this.settings);
    this.registerView(CALENDAR_VIEW_TYPE, (leaf) => new CalendarView(leaf, this));
    this.registerView(SEARCH_VIEW_TYPE, (leaf) => new SearchView(leaf, this));
    this.addSettingTab(new WorkLogSettingTab(this.app, this));
    const ribbonIcon = this.addRibbonIcon("calendar-days", "\u5DE5\u4F5C\u65E5\u5FD7\uFF1A\u6253\u5F00\u4ECA\u65E5\u5DE5\u4F5C\u65E5\u5FD7", async () => {
      await this.openTodayLog();
    });
    ribbonIcon.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showRibbonContextMenu(e);
    });
    this.addCommand({
      id: "open-today",
      name: "\u6253\u5F00\u4ECA\u65E5\u5DE5\u4F5C\u65E5\u5FD7",
      callback: async () => {
        await this.openTodayLog();
      }
    });
    this.addCommand({
      id: "open-calendar",
      name: "\u6253\u5F00\u65E5\u5386\u89C6\u56FE",
      callback: async () => {
        await this.activateCalendarView();
      }
    });
    this.addCommand({
      id: "jump-to-date",
      name: "\u8DF3\u8F6C\u5230\u6307\u5B9A\u65E5\u671F",
      callback: () => {
        new DatePickerModal(this.app, async (date) => {
          await this.fileManager.openAndNavigateToDate(date);
        }).open();
      }
    });
    this.addCommand({
      id: "insert-timestamp",
      name: "\u63D2\u5165\u5F53\u524D\u65F6\u95F4\u5230\u5DE5\u4F5C\u65E5\u5FD7",
      callback: async () => {
        await this.fileManager.insertTimestampEntry();
      }
    });
    this.addCommand({
      id: "repair-structure",
      name: "\u4FEE\u590D\u5F53\u524D\u5E74\u5EA6\u6587\u4EF6\u7ED3\u6784",
      callback: async () => {
        const year = (0, import_obsidian6.moment)().year();
        await this.fileManager.repairYearStructure(year);
      }
    });
    this.addCommand({
      id: "repair-structure-year",
      name: "\u4FEE\u590D\u6307\u5B9A\u5E74\u4EFD\u6587\u4EF6\u7ED3\u6784",
      callback: () => {
        new YearPickerModal(this.app, async (year) => {
          await this.fileManager.repairYearStructure(year);
        }).open();
      }
    });
    this.addCommand({
      id: "regenerate-year-danger",
      name: "\u91CD\u65B0\u751F\u6210\u5F53\u524D\u5E74\u5EA6\u6587\u4EF6\uFF08\u5371\u9669\uFF1A\u5C06\u6E05\u7A7A\u6240\u6709\u5185\u5BB9\uFF09",
      callback: () => {
        const year = (0, import_obsidian6.moment)().year();
        new ConfirmModal(
          this.app,
          `\u26A0\uFE0F \u5371\u9669\u64CD\u4F5C`,
          `\u5373\u5C06\u91CD\u65B0\u751F\u6210 ${year} \u5E74\u5DE5\u4F5C\u65E5\u5FD7\u6587\u4EF6\uFF0C\u8FD9\u5C06\u6E05\u9664\u6240\u6709\u73B0\u6709\u5DE5\u4F5C\u5185\u5BB9\uFF0C\u6B64\u64CD\u4F5C\u65E0\u6CD5\u64A4\u9500\uFF01

\u786E\u8BA4\u7EE7\u7EED\u5417\uFF1F`,
          async () => {
            const filePath = this.fileManager.getFilePath(year);
            const file = this.app.vault.getAbstractFileByPath(filePath);
            const content = await this.fileManager.generateFullYearContent(year);
            if (file) {
              await this.app.vault.modify(file, content);
            } else {
              await this.fileManager.getOrCreateFile(year);
            }
            this.fileManager.invalidateCache(year);
            new import_obsidian6.Notice(`${year} \u5E74\u5DE5\u4F5C\u65E5\u5FD7\u5DF2\u91CD\u65B0\u751F\u6210`);
          }
        ).open();
      }
    });
    this.addCommand({
      id: "show-month-stats",
      name: "\u663E\u793A\u6708\u5EA6\u7EDF\u8BA1",
      callback: async () => {
        const now = (0, import_obsidian6.moment)();
        const stats = await getMonthStats(this, now.year(), now.month() + 1);
        new import_obsidian6.Notice(
          `\u{1F4CA} ${stats.year}\u5E74${stats.month}\u6708\u5DE5\u4F5C\u7EDF\u8BA1
  \u8BB0\u5F55\u5929\u6570\uFF1A${stats.recordedDays} \u5929
  \u603B\u6761\u76EE\u6570\uFF1A${stats.totalEntries} \u6761
  \u603B\u5B57\u6570\uFF1A${stats.totalChars} \u5B57`,
          8e3
        );
      }
    });
    this.addCommand({
      id: "export-log",
      name: "\u5BFC\u51FA\u9009\u4E2D\u7684\u65E5\u5FD7\u8303\u56F4",
      callback: () => {
        new ExportModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "search-log",
      name: "\u641C\u7D22\u5DE5\u4F5C\u65E5\u5FD7",
      callback: async () => {
        await this.activateSearchView();
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          const yearMatch = file.basename.match(/(\d{4})/);
          if (yearMatch) {
            this.fileManager.invalidateCache(parseInt(yearMatch[1]));
          }
        }
      })
    );
    this.app.workspace.onLayoutReady(async () => {
      if (this.settings.autoGenerateYearStructure) {
        const year = (0, import_obsidian6.moment)().year();
        const filePath = this.fileManager.getFilePath(year);
        const existing = this.app.vault.getAbstractFileByPath(filePath);
        if (!existing) {
          try {
            await this.fileManager.getOrCreateFile(year);
          } catch (e) {
          }
        }
      }
      if (!this.app.workspace.getLeavesOfType(CALENDAR_VIEW_TYPE).length) {
        await this.activateCalendarView(false);
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(CALENDAR_VIEW_TYPE);
    this.app.workspace.detachLeavesOfType(SEARCH_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.fileManager) {
      this.fileManager.updateSettings(this.settings);
    }
    this.refreshCalendarViews();
  }
  refreshCalendarViews() {
    for (const leaf of this.app.workspace.getLeavesOfType(CALENDAR_VIEW_TYPE)) {
      const view = leaf.view;
      view.refresh();
    }
  }
  // ─────────────────────────────────────────────────────
  // 核心操作
  // ─────────────────────────────────────────────────────
  async openTodayLog() {
    const today = (0, import_obsidian6.moment)();
    await this.fileManager.openAndNavigateToDate(today);
    for (const leaf of this.app.workspace.getLeavesOfType(CALENDAR_VIEW_TYPE)) {
      const view = leaf.view;
      await view.navigateTo(today.year(), today.month() + 1);
    }
  }
  async activateCalendarView(reveal = true) {
    const existing = this.app.workspace.getLeavesOfType(CALENDAR_VIEW_TYPE);
    if (existing.length > 0) {
      if (reveal)
        this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    let leaf;
    if (this.settings.calendarPosition === "right") {
      leaf = this.app.workspace.getRightLeaf(false);
    } else if (this.settings.calendarPosition === "left") {
      leaf = this.app.workspace.getLeftLeaf(false);
    } else {
      leaf = this.app.workspace.getLeaf("tab");
    }
    if (leaf) {
      await leaf.setViewState({ type: CALENDAR_VIEW_TYPE, active: true });
      if (reveal)
        this.app.workspace.revealLeaf(leaf);
    }
  }
  async activateSearchView() {
    const existing = this.app.workspace.getLeavesOfType(SEARCH_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    if (leaf) {
      await leaf.setViewState({ type: SEARCH_VIEW_TYPE, active: true });
      this.app.workspace.revealLeaf(leaf);
    }
  }
  // ─────────────────────────────────────────────────────
  // Ribbon 右键菜单
  // ─────────────────────────────────────────────────────
  showRibbonContextMenu(e) {
    const menu = document.createElement("div");
    menu.className = "wl-context-menu";
    menu.style.left = `${e.pageX}px`;
    menu.style.top = `${e.pageY}px`;
    const items = [
      {
        text: "\u{1F4C5} \u6253\u5F00\u4ECA\u65E5\u5DE5\u4F5C\u65E5\u5FD7",
        action: async () => {
          await this.openTodayLog();
        }
      },
      {
        text: "\u{1F5D3}\uFE0F \u6253\u5F00\u65E5\u5386\u89C6\u56FE",
        action: async () => {
          await this.activateCalendarView();
        }
      },
      {
        text: "\u{1F50D} \u641C\u7D22\u5DE5\u4F5C\u65E5\u5FD7",
        action: async () => {
          await this.activateSearchView();
        }
      },
      {
        text: "\u{1F527} \u4FEE\u590D\u5F53\u524D\u5E74\u5EA6\u7ED3\u6784",
        action: async () => {
          await this.fileManager.repairYearStructure((0, import_obsidian6.moment)().year());
        }
      }
    ];
    for (const item of items) {
      const el = menu.createDiv({ cls: "wl-context-item", text: item.text });
      el.addEventListener("click", async () => {
        document.body.removeChild(menu);
        await item.action();
      });
    }
    document.body.appendChild(menu);
    const close = () => {
      if (document.body.contains(menu))
        document.body.removeChild(menu);
      document.removeEventListener("click", close);
    };
    setTimeout(() => document.addEventListener("click", close), 0);
  }
};
var DatePickerModal = class extends import_obsidian6.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "\u8DF3\u8F6C\u5230\u6307\u5B9A\u65E5\u671F" });
    const inputEl = contentEl.createEl("input", {
      type: "date",
      cls: "wl-date-input",
      value: (0, import_obsidian6.moment)().format("YYYY-MM-DD")
    });
    const btnRow = contentEl.createDiv("wl-modal-btns");
    const confirmBtn = btnRow.createEl("button", { cls: "mod-cta", text: "\u8DF3\u8F6C" });
    const cancelBtn = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    confirmBtn.addEventListener("click", () => {
      const val = inputEl.value;
      const m = (0, import_obsidian6.moment)(val, "YYYY-MM-DD", true);
      if (m.isValid()) {
        this.close();
        this.onConfirm(m);
      } else {
        new import_obsidian6.Notice("\u65E0\u6548\u7684\u65E5\u671F\u683C\u5F0F");
      }
    });
    cancelBtn.addEventListener("click", () => this.close());
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        confirmBtn.click();
    });
    inputEl.focus();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var YearPickerModal = class extends import_obsidian6.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "\u9009\u62E9\u5E74\u4EFD" });
    const select = contentEl.createEl("select", { cls: "wl-year-sel" });
    const currentYear = (0, import_obsidian6.moment)().year();
    for (let y = currentYear - 5; y <= currentYear + 2; y++) {
      const opt = select.createEl("option", { value: String(y), text: String(y) });
      if (y === currentYear)
        opt.selected = true;
    }
    const btnRow = contentEl.createDiv("wl-modal-btns");
    const confirmBtn = btnRow.createEl("button", { cls: "mod-cta", text: "\u4FEE\u590D" });
    const cancelBtn = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    confirmBtn.addEventListener("click", () => {
      const year = parseInt(select.value);
      this.close();
      this.onConfirm(year);
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ConfirmModal = class extends import_obsidian6.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: this.title, cls: "wl-danger-title" });
    const msgEl = contentEl.createDiv({ cls: "wl-confirm-msg" });
    this.message.split("\n").forEach((line) => {
      msgEl.createDiv({ text: line });
    });
    const btnRow = contentEl.createDiv("wl-modal-btns");
    const confirmBtn = btnRow.createEl("button", { cls: "mod-warning", text: "\u786E\u8BA4\u6267\u884C\uFF08\u4E0D\u53EF\u64A4\u9500\uFF09" });
    const cancelBtn = btnRow.createEl("button", { cls: "mod-cta", text: "\u53D6\u6D88" });
    confirmBtn.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ExportModal = class extends import_obsidian6.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h3", { text: "\u5BFC\u51FA\u5DE5\u4F5C\u65E5\u5FD7" });
    const now = (0, import_obsidian6.moment)();
    const yearRow = contentEl.createDiv("wl-form-row");
    yearRow.createEl("label", { text: "\u5E74\u4EFD\uFF1A" });
    const yearSel = yearRow.createEl("select");
    for (let y = now.year() - 5; y <= now.year(); y++) {
      const opt = yearSel.createEl("option", { value: String(y), text: String(y) });
      if (y === now.year())
        opt.selected = true;
    }
    const rangeRow = contentEl.createDiv("wl-form-row");
    rangeRow.createEl("label", { text: "\u8303\u56F4\uFF1A" });
    const rangeSel = rangeRow.createEl("select");
    rangeSel.createEl("option", { value: "year", text: "\u5168\u5E74" });
    for (let m = 1; m <= 12; m++) {
      const names = [
        "",
        "1\u6708",
        "2\u6708",
        "3\u6708",
        "4\u6708",
        "5\u6708",
        "6\u6708",
        "7\u6708",
        "8\u6708",
        "9\u6708",
        "10\u6708",
        "11\u6708",
        "12\u6708"
      ];
      rangeSel.createEl("option", { value: String(m), text: names[m] });
    }
    rangeSel.value = String(now.month() + 1);
    const fmtRow = contentEl.createDiv("wl-form-row");
    fmtRow.createEl("label", { text: "\u683C\u5F0F\uFF1A" });
    const fmtSel = fmtRow.createEl("select");
    fmtSel.createEl("option", { value: "markdown", text: "Markdown (.md)" });
    fmtSel.createEl("option", { value: "html", text: "HTML (.html)" });
    fmtSel.createEl("option", { value: "json", text: "JSON (.json)" });
    const btnRow = contentEl.createDiv("wl-modal-btns");
    const exportBtn = btnRow.createEl("button", { cls: "mod-cta", text: "\u5BFC\u51FA" });
    const cancelBtn = btnRow.createEl("button", { text: "\u53D6\u6D88" });
    exportBtn.addEventListener("click", async () => {
      const year = parseInt(yearSel.value);
      const rangeVal = rangeSel.value;
      const fmt = fmtSel.value;
      const month = rangeVal === "year" ? void 0 : parseInt(rangeVal);
      const content = await this.plugin.fileManager.exportRange(year, fmt, month);
      if (!content) {
        new import_obsidian6.Notice("\u672A\u627E\u5230\u5BF9\u5E94\u7684\u5DE5\u4F5C\u65E5\u5FD7\u6587\u4EF6");
        return;
      }
      const ext = fmt === "markdown" ? "md" : fmt;
      const suffix = month ? `-${month}\u6708` : "";
      const fileName = `${year}\u5DE5\u4F5C\u65E5\u5FD7${suffix}.${ext}`;
      const filePath = `${this.plugin.settings.logDirectory}/${fileName}`;
      await this.plugin.app.vault.adapter.write(filePath, content);
      new import_obsidian6.Notice(`\u5DF2\u5BFC\u51FA\u5230\uFF1A${filePath}`);
      this.close();
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
